language: node_js
node_js:
- '0.10'
script: npm run-script deploy
# whitelist master branch
branches:
  only:
    - master
env:
  global:
  - GH_REF: github.com/knode/node-meatspace.git
  - secure: RIbIq8hI153J5trRaogHPziSahL9xFM2Vg6Yf3pKGDy5hmHJ/hQjLqkcdqok1MxpmqNqacy6IpYqJukYY7wUmQ5TKhaBa8v9/sPQs9hgfrV6XejmczWnmQaG0KZ14hvegtxL/SJW48N88JcOh9LeLLLarpTgvEAc5ulZuplWG+M=
